minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.150.0+26.1.2
mod_version=2.2

maven_group=io.github.thepro1604
archives_base_name=AdvancedChatLog
malilib_version=26.1.2-0.28.6
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
advancedchat_version=2.3

modrinth_slug=advancedchatlog-next

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatLog
project_url=https://modrinth.com/mod/advancedchatlog-next
project_logo=https://raw.githubusercontent.com/thepro1604/AdvancedChatCore/main/src/main/resources/assets/advancedchatcore/icon.png
project_color=0x134bff
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
