minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2
mod_version=2.3

maven_group=io.github.thepro1604
archives_base_name=AdvancedChatLog
malilib_version=26.2-0.29.5
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
advancedchat_version=2.4

modrinth_slug=advancedchatlog-next

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatLog
project_url=https://modrinth.com/mod/advancedchatlog-next
project_logo=https://raw.githubusercontent.com/thepro1604/AdvancedChatCore/main/src/main/resources/assets/advancedchatcore/icon.png
project_color=0x134bff
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
